import LegalPageLayout from "../components/LegalPageLayout";
import { siteLegal } from "../config/siteLegal";

export default function TermsOfServicePage() {
  return (
    <LegalPageLayout
      eyebrow="Terms of Service"
      title="Terms of Service"
      intro={`These Terms of Service govern your use of ${siteLegal.brandName}, including the website, calculator and modelling tools, account features, and subscription services.`}
    >
      <p>
        <strong>Effective date:</strong> {siteLegal.effectiveDate}
        <br />
        <strong>Last updated:</strong> {siteLegal.lastUpdated}
      </p>

      <p>
        These terms govern your use of {siteLegal.brandName}. By accessing or using the
        service, you agree to be bound by them.
      </p>

      <h2>1. What the service is</h2>
      <p>
        {siteLegal.brandName} provides calculator and modelling tools intended to help
        users estimate pressure washing variables such as nozzle sizing, hose pressure
        loss, and likely at-gun performance. The service may also include accounts, saved
        setups, subscriptions, and related educational or support content.
      </p>

      <h2>2. Informational outputs only</h2>
      <p>
        Outputs generated by {siteLegal.brandName} are estimates based on the information
        entered, built-in assumptions, and the limitations of any model or calculation
        tool. They are provided for general informational and workflow support purposes
        only. They are not a substitute for equipment testing, gauge verification,
        manufacturer specifications, professional advice, site-specific assessment, or
        safe operating judgment.
      </p>

      <h2>3. User responsibility and verification</h2>
      <p>
        You are responsible for checking that any inputs you enter are accurate and for
        independently verifying whether a setup is suitable for your equipment, work
        environment, and intended use. Before relying on any output, you should confirm
        critical details such as equipment ratings, hose condition, nozzle specifications,
        pressure limits, flow requirements, safety devices, and applicable operating
        guidance.
      </p>

      <h2>4. Safety disclaimer</h2>
      <p>
        Pressure washing equipment can be hazardous if used incorrectly. You remain solely
        responsible for safe equipment selection, setup, inspection, operation, training,
        and compliance with any laws, standards, codes, or manufacturer requirements that
        apply to you. Use of {siteLegal.brandName} does not shift that responsibility to us.
      </p>

      <h2>5. No guarantee of accuracy, suitability, or uninterrupted availability</h2>
      <p>
        We aim to make the service useful and reliable, but we do not guarantee that the
        platform will always be accurate, complete, current, error-free, secure, or
        continuously available. Models and assumptions may evolve over time, and real
        equipment performance can vary materially from calculated estimates.
      </p>

      <h2>6. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>use the service unlawfully or in a way that infringes another person's rights;</li>
        <li>attempt to interfere with the platform, its security, or its normal operation;</li>
        <li>reverse engineer, scrape, or copy the service beyond what lawfully applies;</li>
        <li>misuse accounts, credentials, billing flows, or access controls;</li>
        <li>use the service in a misleading way or falsely imply endorsement by us.</li>
      </ul>

      <h2>7. Accounts</h2>
      <p>
        Some features may require an account. You are responsible for maintaining the
        confidentiality of your login credentials and for activities that occur under your
        account. You must provide reasonably accurate information and keep it updated.
      </p>

      <h2>8. Free and paid features</h2>
      <p>
        We may offer both free and paid features, including a {siteLegal.brandName} Pro
        subscription. Features, limits, eligibility, pricing, and inclusions may change
        over time. We may also introduce, modify, or discontinue features in good faith as
        the platform evolves.
      </p>

      <h2>9. Billing, renewals, and cancellations</h2>
      <p>
        Paid subscriptions may renew automatically unless cancelled before the next
        billing cycle, subject to the billing terms presented at checkout. Billing may be
        managed through <strong>{siteLegal.billingProvider}</strong> or another payment
        provider. You authorise the applicable provider to charge the fees associated with
        your selected plan.
      </p>
      <p>
        Unless required otherwise by law, subscription fees are generally non-refundable
        for partial billing periods or unused time. You should update this section to
        reflect any specific refund, trial, tax, invoicing, GST, or cancellation wording
        that applies to your business and checkout flow.
      </p>

      <h2>10. Trials, promotions, and plan changes</h2>
      <p>
        We may offer trials, discounts, grandfathered pricing, credits, or promotional
        access from time to time. Any such offer may be subject to additional terms
        presented at the time of the offer. We may also allow upgrades, downgrades, or
        plan changes, which may take effect immediately or from the next billing cycle.
      </p>

      <h2>11. Intellectual property</h2>
      <p>
        The {siteLegal.brandName} website, brand, design, content, code, calculator
        logic, visual presentation, and related materials are owned by us or our
        licensors, unless otherwise stated. These terms do not transfer any ownership
        rights to you. You may use the service for its intended purpose, but you may not
        reproduce, sell, license, republish, or exploit material from the service except
        as permitted by law or with our written permission.
      </p>

      <h2>12. User content and saved data</h2>
      <p>
        You retain responsibility for information you submit, store, or save through the
        platform, including saved setups and account content. By submitting or storing
        content through the service, you grant us a limited right to host, process, back
        up, transmit, and display that content as reasonably necessary to operate and
        improve the service.
      </p>

      <h2>13. Suspension or termination</h2>
      <p>
        We may suspend, restrict, or terminate access to the service where reasonably
        necessary, including for maintenance, security, misuse, non-payment, legal
        compliance, or platform changes. You may stop using the service at any time and
        cancel any subscription in accordance with the billing terms that apply.
      </p>

      <h2>14. Third-party services</h2>
      <p>
        The platform may rely on third-party services such as hosting, analytics,
        authentication, databases, support tools, and payment processing. We are not
        responsible for separate third-party services to the extent permitted by law,
        although we try to select reputable providers.
      </p>

      <h2>15. Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, we exclude liability for indirect,
        incidental, special, or consequential loss, loss of profits, loss of revenue, loss
        of data, loss of business opportunity, or damage arising from or related to your
        use of, or inability to use, the service.
      </p>
      <p>
        To the maximum extent permitted by law, our total liability for claims arising out
        of or in connection with the service will be limited to the amount you paid us for
        the relevant paid service during the 12 months before the event giving rise to the
        claim, or if you only used the free service, a nominal amount of AUD $100.
      </p>
      <p>
        Nothing in these terms excludes rights or remedies that cannot be excluded under
        Australian Consumer Law or any other applicable law. Where a guarantee or remedy
        cannot be excluded but can be limited, our liability is limited to the maximum
        extent permitted by law.
      </p>

      <h2>16. Indemnity</h2>
      <p>
        To the extent permitted by law, you agree to indemnify us against losses, claims,
        damages, liabilities, and costs arising from your misuse of the service, your
        breach of these terms, or your unlawful conduct.
      </p>

      <h2>17. Changes to the service or terms</h2>
      <p>
        We may update the service and these terms from time to time. Material changes will
        take effect when published or as otherwise communicated. Continued use of the
        service after updated terms take effect constitutes acceptance of the revised terms.
      </p>

      <h2>18. Governing law</h2>
      <p>
        These terms are governed by the laws of <strong>{siteLegal.jurisdiction}</strong>,
        unless mandatory law requires otherwise. You and {siteLegal.brandName} submit to
        the non-exclusive jurisdiction of the courts of New South Wales.
      </p>

      <h2>19. Contact</h2>
      <p>
        For legal or support enquiries, contact <strong>{siteLegal.contactEmail}</strong>.
      </p>
    </LegalPageLayout>
  );
}
