import LegalPageLayout from "../components/LegalPageLayout";
import { siteLegal } from "../config/siteLegal";

export default function TermsOfServicePage() {
  return (
    <LegalPageLayout
      eyebrow="TERMS OF SERVICE"
      title="Terms of Service"
      intro={`These Terms of Service govern your use of ${siteLegal.brandName}, including the website, calculator and modelling tools, account features, saved setups, and subscription services.`}
    >
      <p>
        <strong>Effective date:</strong> {siteLegal.effectiveDate}
        <br />
        <strong>Last updated:</strong> {siteLegal.lastUpdated}
      </p>

      <p>
        These Terms of Service apply when you access or use {siteLegal.brandName}.
        By using the service, you agree to these terms. If you do not agree, you
        should not use the service.
      </p>

      <h2>1. What the service is</h2>
      <p>
        {siteLegal.brandName} provides pressure washer calculator and modelling
        tools intended to help users estimate setup variables such as nozzle
        sizing, hose pressure loss, pressure and flow relationships, and likely
        at-gun performance. The service may also include account features, saved
        setups, subscriptions, educational content, support content, and related
        tools.
      </p>

      <h2>2. Informational outputs only</h2>
      <p>
        Outputs generated by {siteLegal.brandName} are estimates based on the
        information entered, built-in assumptions, and the limitations of any
        model or calculation tool. They are provided for general informational
        and workflow support purposes only.
      </p>
      <p>
        The service is not a substitute for physical testing, gauge verification,
        manufacturer specifications, professional advice, site-specific
        assessment, safe operating procedures, or your own judgment. Real-world
        equipment performance can vary from calculated estimates.
      </p>

      <h2>3. User responsibility and verification</h2>
      <p>
        You are responsible for checking that any inputs you enter are accurate
        and for independently verifying whether a setup is suitable for your
        equipment, work environment, and intended use. Before relying on any
        output, you should confirm critical details such as equipment ratings,
        hose condition, nozzle specifications, pressure limits, flow requirements,
        safety devices, and applicable operating guidance.
      </p>

      <h2>4. Safety disclaimer</h2>
      <p>
        Pressure washing equipment can be hazardous if selected, configured, or
        used incorrectly. You remain solely responsible for safe equipment
        selection, setup, inspection, operation, training, supervision, and
        compliance with any laws, standards, codes, or manufacturer requirements
        that apply to you. Use of {siteLegal.brandName} does not transfer that
        responsibility to us.
      </p>

      <h2>5. Accounts and security</h2>
      <p>
        Some features may require an account. You are responsible for maintaining
        the confidentiality of your login credentials and for activity that
        occurs under your account. You must provide reasonably accurate account
        information and keep it updated.
      </p>

      <h2>6. Free and paid features</h2>
      <p>
        We may offer both free and paid features, including a {siteLegal.brandName}{" "}
        Pro subscription. Features, limits, eligibility, pricing, inclusions, and
        availability may change over time as the platform evolves.
      </p>

      <h2>7. Billing, renewals, and cancellations</h2>
      <p>
        Paid subscriptions may renew automatically unless cancelled before the
        next billing cycle, subject to the billing terms presented at checkout.
        Billing may be managed through <strong>{siteLegal.billingProvider}</strong>{" "}
        or another payment provider. You authorise the applicable payment provider
        to charge the fees associated with your selected plan.
      </p>
      <p>
        Unless required otherwise by law, subscription fees are generally
        non-refundable for partial billing periods or unused time. Any free trial,
        promotional pricing, tax, GST, invoicing, cancellation, upgrade, or
        downgrade terms presented at checkout or in related billing materials will
        also apply.
      </p>

      <h2>8. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul className="my-5 ml-6 list-disc space-y-2 text-slate-700 marker:text-slate-500">
        <li className="pl-1">
          use the service unlawfully or in a way that infringes another person's
          rights;
        </li>
        <li className="pl-1">
          interfere with the service, its security, its infrastructure, or its
          normal operation;
        </li>
        <li className="pl-1">
          bypass, misuse, or attempt to defeat account, subscription, billing, or
          access controls;
        </li>
        <li className="pl-1">
          submit malicious code, attempt unauthorised access, or test the service
          for vulnerabilities without written permission;
        </li>
        <li className="pl-1">
          use the service in a misleading way or falsely imply endorsement,
          partnership, or affiliation with us;
        </li>
        <li className="pl-1">
          use automated scraping, crawling, harvesting, or extraction tools unless
          we have given written permission or the activity is clearly permitted by
          law.
        </li>
      </ul>

      <h2>9. Copying, reverse engineering, and competing use</h2>
      <p>
        You may use {siteLegal.brandName} for normal personal or business
        calculation purposes. You must not copy, reproduce, clone, modify,
        scrape, reverse engineer, decompile, resell, redistribute, frame, mirror,
        or commercially exploit the service, its code, compiled assets, design,
        layout, calculator workflows, content, branding, or visual presentation
        without written permission, except to the extent that such restriction is
        prohibited by law.
      </p>
      <p>
        You must not use the service, or information extracted from the service,
        to create, train, improve, market, or operate a substantially similar or
        competing product or service without written permission, except to the
        extent that such restriction is prohibited by law.
      </p>

      <h2>10. Intellectual property</h2>
      <p>
        {siteLegal.brandName}, including its website, brand, logo, design,
        content, source code, compiled software, calculator workflows,
        documentation, user interface, visual presentation, and related materials,
        is owned by us or our licensors unless otherwise stated. These terms do
        not transfer any ownership rights to you.
      </p>
      <p>
        You may use the service only for its intended purpose and in accordance
        with these terms. No part of the service may be copied, republished,
        licensed, sold, redistributed, or otherwise exploited except as permitted
        by law or with our written permission.
      </p>

      <h2>11. Feedback and suggestions</h2>
      <p>
        If you send us feedback, ideas, suggestions, bug reports, or feature
        requests, you allow us to use that feedback without restriction or
        compensation to you. You should not submit anything confidential through a
        feedback form unless we have separately agreed to receive it on that
        basis.
      </p>

      <h2>12. User content and saved data</h2>
      <p>
        You retain responsibility for information you submit, store, or save
        through the platform, including saved setups and account content. By
        submitting or storing content through the service, you grant us a limited
        right to host, process, back up, transmit, and display that content as
        reasonably necessary to operate, secure, support, and improve the service.
      </p>

      <h2>13. Third-party services</h2>
      <p>
        The platform may rely on third-party services such as hosting, analytics,
        authentication, databases, support tools, email delivery, and payment
        processing. Those services may have their own terms and privacy practices.
        We are not responsible for separate third-party services to the extent
        permitted by law, although we try to select reputable providers.
      </p>

      <h2>14. Availability and changes to the service</h2>
      <p>
        We aim to make the service useful and reliable, but we do not guarantee
        that it will always be accurate, complete, current, error-free, secure, or
        continuously available. We may update, modify, suspend, limit, or
        discontinue parts of the service in good faith as the platform evolves.
      </p>

      <h2>15. Suspension or termination</h2>
      <p>
        We may suspend, restrict, or terminate access to the service where
        reasonably necessary, including for maintenance, security, misuse,
        suspected misuse, non-payment, legal compliance, or platform changes. You
        may stop using the service at any time and cancel any subscription in
        accordance with the billing terms that apply.
      </p>

      <h2>16. Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, we exclude liability for indirect,
        incidental, special, or consequential loss, loss of profits, loss of
        revenue, loss of data, loss of business opportunity, equipment damage,
        downtime, or damage arising from or related to your use of, or inability
        to use, the service.
      </p>
      <p>
        To the maximum extent permitted by law, our total liability for claims
        arising out of or in connection with the service will be limited to the
        amount you paid us for the relevant paid service during the 12 months
        before the event giving rise to the claim. If you only used the free
        service, our total liability will be limited to AUD $100.
      </p>

      <h2>17. Australian Consumer Law</h2>
      <p>
        Nothing in these terms excludes, restricts, or modifies rights, remedies,
        guarantees, warranties, or liabilities that cannot be excluded, restricted,
        or modified under Australian Consumer Law or any other applicable law.
        Where a guarantee or remedy cannot be excluded but can be limited, our
        liability is limited to the maximum extent permitted by law.
      </p>

      <h2>18. Indemnity</h2>
      <p>
        To the extent permitted by law, you agree to indemnify us against losses,
        claims, damages, liabilities, and costs arising from your misuse of the
        service, your breach of these terms, or your unlawful conduct.
      </p>

      <h2>19. Changes to these terms</h2>
      <p>
        We may update these terms from time to time. Material changes will take
        effect when published or as otherwise communicated. Continued use of the
        service after updated terms take effect constitutes acceptance of the
        revised terms.
      </p>

      <h2>20. Governing law</h2>
      <p>
        These terms are governed by the laws of <strong>{siteLegal.jurisdiction}</strong>,
        unless mandatory law requires otherwise. You and {siteLegal.brandName}{" "}
        submit to the non-exclusive jurisdiction of the courts of that
        jurisdiction.
      </p>

      <h2>21. Contact</h2>
      <p>
        For legal or support enquiries, contact <strong>{siteLegal.contactEmail}</strong>.
      </p>
    </LegalPageLayout>
  );
}
